project:
  type: default
  pre-render:
    - Rscript tools/copy_figures.R
  post-render: 
    - Rscript tools/embed_bbl.R
    - bash tools/move_tex_source_files.sh
    - bash tools/remove_quarto_interim_files.sh
    - Rscript tools/generate_diff.R

execute:
  echo: false
  message: false
  warning: false

bibliography: references.bib
